table Orders
	lineageTag: 3dee237e-7318-43e7-bb16-4fcf467e9ae1

	measure '_ Sales YoY%' =
			
			(VAR __PREV_YEAR =
					CALCULATE(
						SUM('Orders'[Sales]),
						DATEADD('Orders'[Order Date].[Date], -1, YEAR)
					)
				RETURN
					DIVIDE(SUM('Orders'[Sales]) - __PREV_YEAR, __PREV_YEAR))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1b2f467d-7909-4bc2-beb2-3b2e718a280f

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "YearOverYear",
				  "version": 0
				}

		changedProperty = FormatString

	measure '_ Sales MoM%' =
			
			(VAR __PREV_MONTH =
					CALCULATE(
						SUM('Orders'[Sales]),
						DATEADD('Orders'[Order Date].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE(SUM('Orders'[Sales]) - __PREV_MONTH, __PREV_MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c10de8df-ad2f-42fc-a91c-453d93282284

	measure '_ Sales Per Customer' = SUM(Orders[Sales])/DISTINCTCOUNT(Orders[Customer ID])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bce494b1-aa9b-476f-8d5e-d8fc15a5cf2e

	measure '_ Profit YoY%' =
			
			(VAR __PREV_YEAR =
					CALCULATE(
						SUM('Orders'[Profit]),
						DATEADD('Orders'[Order Date].[Date], -1, YEAR)
					)
				RETURN
					DIVIDE(SUM('Orders'[Profit]) - __PREV_YEAR, __PREV_YEAR))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: ee65f1bb-f385-45a4-a15f-1efac7d2c963

	measure '_ Profit MoM%' =
			
			(VAR __PREV_MONTH =
					CALCULATE(
						SUM('Orders'[Profit]),
						DATEADD('Orders'[Order Date].[Date], -1, MONTH)
					)
				RETURN
					DIVIDE(SUM('Orders'[Profit]) - __PREV_MONTH, __PREV_MONTH))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 20c0fd0a-772c-4816-bffd-8ea96be2bd2d

	measure '_ Profit Per Customer' = SUM(Orders[Profit])/DISTINCTCOUNT(Orders[Customer ID])
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 6ed21faf-12ab-4cf1-842d-caf7a8d279c9

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure '_ Profit per Order' = SUM(Orders[Profit])/DISTINCTCOUNT(Orders[Order ID])
		lineageTag: 2801f81c-00b5-40b8-bd32-182c42c7b4fa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_ % Return Order' = COUNT(Returns[Order ID])/DISTINCTCOUNT(Orders[Order ID])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 22d572fd-3823-4875-b958-0659ef87dcaa

	measure '_ Products Returned' = COUNTX(FILTER(Orders, Orders[isReturned] = 1), Orders[Customer ID])
		formatString: 0
		lineageTag: 9a850904-a4da-4cd0-95d9-8ee7b3039995

	measure '_ Avg Product per Customer' = COUNT(Orders[Product ID])/DISTINCTCOUNT(Orders[Customer ID])
		lineageTag: 7ae01c05-c8e3-4323-946a-72c1491a7f11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '_ Order Accuracy' = DIVIDE((DISTINCTCOUNT(Orders[Order ID]) - COUNT(Returns[Order ID])), DISTINCTCOUNT(Orders[Order ID]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 58ae949b-029e-478d-8cc8-791c99fa364b

	measure 'Order Prev Year' =
			
			var prev_year_qty = CALCULATE(SUM(Orders[Quantity]), DATEADD(Orders[Order Date].[Date], -1, YEAR))
			return (SUM(Orders[Quantity]) - prev_year_qty)
		formatString: 0
		lineageTag: a6852702-7474-4e1e-a133-6d7af82a2357

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 68e6b083-89ab-4ae1-8862-041e5dcce612
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: eb1756f1-351f-492b-840d-458bd948e17b
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 307b6eca-8880-4513-a9b0-927da216706e
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: baf92575-7ca3-4226-84e8-728d7d0cd19b
			defaultHierarchy: LocalDateTable_35f8b3df-2e65-4628-b3ed-21599c7cf8ae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9e6227b-85b1-4a2a-bd6f-49db32562cb0
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 02ddba8c-23d0-4d52-872d-54d2e072d1c9
			defaultHierarchy: LocalDateTable_7c2543f3-9df8-46bc-837d-56212f6d6a22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 0d17c345-3e01-4280-b3ab-bc7fba9dce72
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 2d0a24a1-64e0-4c07-881d-d65b74b6268f
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 17f6dd75-2193-4330-8b7c-9f459551b842
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 7eea5037-5e43-4044-9ac4-a781cc7a17db
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 2874e122-4274-4350-a835-9ff167d49342
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 8bd4c86f-6a84-4a9d-bc70-054f118ee708
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: fc8ec6d1-ca8d-44aa-b387-da523fefb1f3
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: c68288e2-db93-4bd6-b141-6d1a821960ed
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 81a02223-4342-4078-8d97-c13fb4ee40e0
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 022a1da8-5c03-440b-b6cf-6721cd52eeb1
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 954efab9-8af6-4e85-83f2-918893cd1653
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: c0d04a3b-fb30-413f-a22d-f3dabb229dff
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: d614ad2d-e864-41ae-82de-515ac8714d94
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Orders","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Sales
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8f936baf-af8d-4f8a-b614-a93dda3a4a8a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Orders","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 1ec64acb-0761-4908-9cab-c495343a1f1c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		formatString: 0.00
		lineageTag: c64747d8-d773-4874-881b-92619ad881a1
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

	column Profit
		dataType: double
		formatString: \$#,0.00;-\$#,0.00;\$#,0.00
		lineageTag: e63807ea-b0aa-4e21-928f-684c80660e60
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Orders","TableItemName":"Product Name (clusters)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Price = ```
			(Orders[Sales] - Orders[Profit])/Orders[Quantity] 
			```
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ca045a8d-a9fc-4732-9c88-c967a88af84a
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column isReturned
		dataType: int64
		formatString: 0
		lineageTag: 168b2131-7fd7-46d6-af80-e9277f962c3f
		summarizeBy: sum
		sourceColumn: isReturned

		annotation SummarizationSetBy = Automatic

	column 'Return Order ID'
		dataType: string
		lineageTag: 6eac6b51-6797-42f0-a55a-406cc15ebaa2
		summarizeBy: none
		sourceColumn: Return Order ID

		annotation SummarizationSetBy = Automatic

	column 'Processing Time' = DATEDIFF(Orders[Order Date], Orders[Ship Date], DAY)
		dataType: int64
		formatString: 0
		lineageTag: aedba9af-3ceb-4095-b9a0-87ce1bae6047
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	/// Clusters for Product Name
	column 'Product Name (clusters)' = ```
			VAR __ClusterValue = 
				LOOKUPVALUE(
					'ClusterMappingTable'[ClusterId],
					'ClusterMappingTable'[Product_Name],
					'Orders'[Product Name]
				)
			
			RETURN
				SWITCH(
					__ClusterValue,
					BLANK(),
					BLANK(),
					CONCATENATE("Cluster", __ClusterValue)
				)
			```
		dataType: string
		lineageTag: 6766d490-965e-4727-81b1-b559c46bb29f
		summarizeBy: none
		isDataTypeInferred

		extendedProperty GroupingMetadata =
				{
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Orders"
				          }
				        },
				        "Property": "Product Name"
				      }
				    }
				  ],
				  "version": 0
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"o","Entity":"Orders"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"o"}},"Property":"Product Name"}}],"PartitionTable":{"Definition":{"TableDefinition":{"Version":2,"From":[{"Name":"o","Entity":"Orders"}],"Where":[],"OrderBy":[],"Select":[{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"Orders.Product Name"},"Name":"Orders.Product Name"},{"Column":{"Expression":{"TransformTableRef":{"Source":"output0"}},"Property":"clusterId"},"Name":"clusterId"}],"GroupBy":[],"Transform":[{"Name":"KMeansClustering","Algorithm":"KMeansClustering","Input":{"Parameters":[{"Literal":{"Value":"4L"},"Name":"NumberOfClusters"}],"Table":{"Name":"input0","Columns":[{"Role":"Attribute","Expression":{"Aggregation":{"Function":0,"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"o"}},"Property":"Profit"}}},"Name":"Sum(Orders.Profit)"}},{"Role":"Attribute","Expression":{"Aggregation":{"Function":0,"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"o"}},"Property":"Sales"}}},"Name":"Sum(Orders.Sales)"}},{"Role":"Item","Expression":{"Column":{"Expression":{"SourceRef":{"Source":"o"}},"Property":"Product Name"},"Name":"Orders.Product Name"}}]}},"Output":{"Table":{"Name":"output0","Columns":[{"Expression":{"Column":{"Expression":{"TransformTableRef":{"Source":"input0"}},"Property":"Orders.Product Name"},"Name":"Orders.Product Name"}},{"Role":"Series","Expression":{"TransformOutputRoleRef":{"Role":"ClusterId"},"Name":"clusterId"}}]}}}]},"ItemIdColumns":["Orders.Product Name"],"PartitionIdColumn":"clusterId","Partitions":[{"PartitionIds":[{"Literal":{"Value":"null"}}]}],"DefaultPartitionPrefix":"Cluster"},"Result":{"TableName":"ClusterMappingTable","PartitionIdColumn":"ClusterId","ItemIdMappings":[[{"PartitionTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"ClusterMappingTable"}},"Property":"Product_Name"}},"SourceTableColumn":{"Column":{"Expression":{"SourceRef":{"Entity":"Orders"}},"Property":"Product Name"}}}]]}}}

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Qrios Tech\Downloads\Task\Task\Data\Sample - Superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Order ID"}, Returns, {"Order ID"}, "Returns", JoinKind.LeftOuter),
				    #"Expanded Returns" = Table.ExpandTableColumn(#"Merged Queries", "Returns", {"Returned", "Order ID"}, {"Returns.Returned", "Returns.Order ID"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Returns",{{"Returns.Returned", "isReturned"}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Renamed Columns",{{"Returns.Order ID", "Return Order ID"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Yes","1",Replacer.ReplaceText,{"isReturned"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"0",Replacer.ReplaceValue,{"isReturned"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value1",{{"isReturned", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

